version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "80:80"

volumes:
  node_modules:
