version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "80:80"

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: acme_widget
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3307:3306

volumes:
  node_modules:
  db_data:
